// Code generated by entc, DO NOT EDIT.

package tree

const (
	// Label holds the string label denoting the tree type in the database.
	Label = "tree"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeTarget holds the string denoting the target edge name in mutations.
	EdgeTarget = "target"
	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"

	// Table holds the table name of the tree in the database.
	Table = "trees"
	// TargetTable is the table the holds the target relation/edge. The primary key declared below.
	TargetTable = "tree_target"
	// SourceTable is the table the holds the source relation/edge. The primary key declared below.
	SourceTable = "tree_target"
)

// Columns holds all SQL columns for tree fields.
var Columns = []string{
	FieldID,
}

var (
	// TargetPrimaryKey and TargetColumn2 are the table columns denoting the
	// primary key for the target relation (M2M).
	TargetPrimaryKey = []string{"tree_id", "source_id"}
	// SourcePrimaryKey and SourceColumn2 are the table columns denoting the
	// primary key for the source relation (M2M).
	SourcePrimaryKey = []string{"tree_id", "source_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
