// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// TreesColumns holds the columns for the "trees" table.
	TreesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
	}
	// TreesTable holds the schema information for the "trees" table.
	TreesTable = &schema.Table{
		Name:        "trees",
		Columns:     TreesColumns,
		PrimaryKey:  []*schema.Column{TreesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// TreeTargetColumns holds the columns for the "tree_target" table.
	TreeTargetColumns = []*schema.Column{
		{Name: "tree_id", Type: field.TypeString},
		{Name: "source_id", Type: field.TypeString},
	}
	// TreeTargetTable holds the schema information for the "tree_target" table.
	TreeTargetTable = &schema.Table{
		Name:       "tree_target",
		Columns:    TreeTargetColumns,
		PrimaryKey: []*schema.Column{TreeTargetColumns[0], TreeTargetColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "tree_target_tree_id",
				Columns: []*schema.Column{TreeTargetColumns[0]},

				RefColumns: []*schema.Column{TreesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "tree_target_source_id",
				Columns: []*schema.Column{TreeTargetColumns[1]},

				RefColumns: []*schema.Column{TreesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TreesTable,
		TreeTargetTable,
	}
)

func init() {
	TreeTargetTable.ForeignKeys[0].RefTable = TreesTable
	TreeTargetTable.ForeignKeys[1].RefTable = TreesTable
}
