version: "3.3"

services:
    grpc-server:
        image: grpc-server:dev
        build:
            context: .
        ports:
            - 50051:50051
    postgres:
        image: 'postgres:latest'
        ports:
            - 9920:5432 
        environment:
            - POSTGRES_DB=gorm
            - POSTGRES_USER=gorm
            - POSTGRES_PASSWORD=gorm
volumes: 
    grpc: