version: "3.3"

services:
    grpc-server:
        container_name: grpc-server
        image: grpc-server:postgres
        build:
            context: .
        environment: 
            - PG_HOST=postgres-server
            - PG_PORT=5432
            - PG_USER=postgres
            - PG_PASSWORD=laforge
            - PG_DB=postgres
        ports:
            - 50051:50051

    postgres-server:
        container_name: postgres-server
        image: bitnami/postgresql
        expose: 
            - 5432
        volumes: 
            - grpc_postgres:/bitnami/postgresql
        environment: 
            - POSTGRESQL_PASSWORD=laforge

    pgadmin4:
        container_name: pgadmin
        hostname: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=laforge@laforge.local
            - PGADMIN_DEFAULT_PASSWORD=laforge
        ports:
            - "8081:80"

volumes: 
    grpc_postgres: