version: "3.3"

services:
    grpc-server:
        container_name: grpc-server
        image: grpc-server:redis
        build:
            context: .
        environment: 
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - REDIS_PASSWORD=laforge
        ports:
            - 50051:50051

    redis-server:
        container_name: redis-server
        image: bitnami/redis
        expose: 
            - 6379
        volumes: 
            - grpc_redis:/bitnami/redis/data
        environment: 
            - REDIS_PASSWORD=laforge

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis-server:6379:0:laforge
        ports:
            - "8081:8081"

volumes: 
    grpc_redis: